services:
  mediamtx:
    build:
      context: ./apps/streaming
      dockerfile: Dockerfile
    container_name: streaming
    ports:
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
      - "8554:8554"
      - "9997:9997"
    restart: always

  nestjs:
    build:
      context: ./apps/avynix-streaming
      dockerfile: Dockerfile
    container_name: streaming_api
    ports:
      - "5000:5000"
    environment:
      # MediaMTX connection (inside Docker, use service name)
      MEDIAMTX_CONTROL_BASE: http://mediamtx:9997
      MEDIAMTX_HLS_BASE: http://localhost:8888
      MEDIAMTX_WEBRTC_BASE: http://localhost:8889
      MEDIAMTX_USER: admin
      MEDIAMTX_PASS: admin

      # NestJS own settings
      PORT: 5000
      BASE_URL: http://localhost:5000
    depends_on:
      - mediamtx
    restart: always

  nextjs:
    build:
      context: ./apps/rtsp-feed
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      # internal (for Next.js backend → MediaMTX)
      NEXT_PUBLIC_MEDIAMTX_CONTROL_BASE: http://localhost:5000

    depends_on:
      - nestjs
      - mediamtx
    restart: always
